### PR TITLE
fix: Update components based on Figma

### PR DESCRIPTION
**Pull request by chrisllontop**

### CODE REVIEW

**Comment by osbornm** [comment]
@nathanyoung this makes the components match the figma file closer, it's not a blocker and I want your take. IMO it's okay if we take it and its okay if we don't.

**Comment by nathanyoung** [comment]
@osbornm what figma file are we referring to?

**Comment by nathanyoung** [comment]
The typography scale that's in figma (caption, body 1, body 2, h1-h6, etc) doesn't really match what's in design tokens (xs-5xl), but I see you just want to make H1's 64px, so ok with me.

**Comment by chrisllontop** [comment]
@nathanyoung We haven't fully modified the tokens or libraries to align them with the design because we didn't know if the tokens coming from Palmetto would be used without modifications in Hyphen. If necessary, I can put all the Figma tokens in the library to make them match.

**Pull request merged**
